main:
  - name: Home
    url: /
    weight: 1
  - name: Blog
    url: blog/
    weight: 2
  - name: Contact
    url: contact/
    weight: 3
footer:
  - name: About
    url: about/
    weight: 1
  - name: Privacy Policy
    url: privacy-policy/
    weight: 3
