apiVersion: v1
kind: ServiceAccount
metadata:
  name: blackbox
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blackbox-roles
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources:
    - pods
    verbs:
    - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: blackbox-rolebinding
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: blackbox
    namespace: monitoring
roleRef:
  kind: Role
  name: blackbox-roles
  apiGroup: rbac.authorization.k8s.io
---
kind: Service
apiVersion: v1
metadata:
  name: blackbox-exporter-svc
  labels:
    app: blackbox-exporter
  annotations:
      prometheus.io/scrape: 'true'
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: http
      port: 9115
      protocol: TCP
  selector:
    app: blackbox-exporter
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: blackbox-exporter-ds
  namespace: monitoring
  labels:
    app: blackbox-exporter
spec:
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      serviceAccountName: blackbox
      hostAliases:
        - hostnames:
          - kube-vip
          ip: 10.168.0.10
      restartPolicy: Always
      containers:
        - name: blackbox-exporter
          image: quay.io/prometheus/blackbox-exporter:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          args:
            - "--config.file=/etc/config/blackbox.yaml"
          ports:
            - containerPort: 9115
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - mountPath: /etc/config
              name: blackbox-exporter-config
        - name: configmap-reload
          image: "jimmidyson/configmap-reload:latest"
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
          args:
            - --volume-dir=/etc/config
            - --webhook-url=http://localhost:9115/-/reload
          volumeMounts:
            - mountPath: /etc/config
              name: blackbox-exporter-config
              readOnly: true
      volumes:
        - name: blackbox-exporter-config
          configMap:
            name: blackbox-exporter-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: blackbox-exporter-config
  labels:
    app: blackbox-exporter
data:
  blackbox.yaml: |
    modules:
      tcp_connect:
        prober: tcp
        timeout: 5s
      icmp:
        prober: icmp
        timeout: 5s
      http_2xx:
        prober: http
        timeout: 5s
        http:
          method: GET
          no_follow_redirects: false
          preferred_ip_protocol: ip4
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2
          valid_status_codes:
          - 200
          - 401
          - 403
          tls_config:
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token