controller:
  kind: DaemonSet
  containerPort:
    http: 80
    https: 443
  dnsPolicy: ClusterFirstWithHostNet
  hostNetwork: true
  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443
  ingressClassResource:
    name: nginx
    default: true
  ingressClass: nginx