apiVersion: v1
kind: Service
metadata:
  name: node-exporter-svc
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9100
    protocol: TCP
  selector:
    app: node-exporter
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter-ds
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - image:  quay.io/prometheus/node-exporter:latest
        args:
        - "--path.procfs=/node/proc"
        - "--path.sysfs=/node/sys"
        - "--collector.disable-defaults"
        - "--collector.cpu"
        - "--collector.cpu.info"
        - "--collector.cpufreq"
        - "--collector.meminfo"
        - "--collector.hwmon"
        - "--collector.netdev"
        - "--collector.filesystem"
        - "--collector.diskstats"
        - "--collector.os"
        - "--collector.systemd"
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: scrape
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        volumeMounts:
        - name: proc
          readOnly:  true
          mountPath: /node/proc
        - name: sys
          readOnly: true
          mountPath: /node/sys
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys